#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=offi
bspc config focus_follows_pointer true
feh --bg-fill /home/${USER}/Pictures/fondo.jpg
xsetroot -cursor_name left_ptr &
bash ~/.config/polybar/launch.sh --cuts
pkill picom
picom -f --daemon --config "${HOME}/.config/picom/picom.conf" &
# Iniciar xss-lock con hollywood-activate
xss-lock -- hollywood-activate &
